### ISSUE TITLE
Check social approach mechanisms for correctness

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/knowledge-base#102]
Verify mechanisms in [social approach vignette](https://github.com/Display-Lab/knowledge-base/tree/main/vignettes/social_approach_vignette), especially the optimism mechanism, have correct descriptions according to the literature.

**Comment by mackgalante** [comment]
Need to verify language for mechanisms in social approach is sufficient/correct (see optimism especially)

**Comment by 00hchung99** [comment]
From Carey et al. 2019 optimism is "confidence that things will happen for the best or that desired goals will be
attained" Zach will update the readme accordingly

**Comment by 00hchung99** [comment]
Carey et al. paper linked in the causal pathways spreadsheet should define all the mechanisms

**Comment by mackgalante** [comment]
Done, see pull request #122 
- note: implemented carey et. al.'s work in goal approach and goal loss templates as well, see pull #119
