### ISSUE TITLE
add CEDAR message template id to message library spreadsheet

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#114]
add the CEDAR message template ID to column C of the message library spreadsheet to track the completion of each template from the message library: https://docs.google.com/spreadsheets/d/1h81ZmTqMWvWDcpLIr5IFW-AAmEiqQAPB4ZtyQtY87HQ/edit#gid=439820594

**Comment by mackgalante** [comment]
Seems to be complete as of 9/15
