### ISSUE TITLE
What string format should be used for dynamic key messages?

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/knowledge-base#12]
Key messages have been discussed in a way that assumes value substitution will be available.  Essentially string interpolation has been expected such that a variable value will be inserted for X in the example, "Your performance is X".

The precise format of dynamic key message strings such that interpolation will be supported has yet to be determined.  **What string format should be used for dynamic key messages?**

Considerations include what systems are expected to be interpreting this string?  R, Ruby, Python, Java?  Baking in one system as the assumed interpreter means any other system will have to extract and translate for its own templating engine.  Coming up with a new one denovo will mean all interpreting systems will have to translate.

E.g. 

| Kind of Syntax | Example |
|-------------|---------------|
| Ruby's string interpolation syntax      |    "Your performance is #{X}"      |
| Ruby's ERB syntax      |    "Your performance is <%= X %>"    |
| Python's Jinja2      |   "Your performance is  {{X}}"    |
| Java's Thymeleaf      |   "Your performance is #{X}"    |
| Java's FreeMarker      |   "Your performance is ${X}"    |
| R's Markdown |   "Your performance is \`r X\`"    |
| R's Sweave  |   "Your performance is \Sexpr{X}"    |
| sprintf |   "Your performance is %d"    |
| bash | "Your performance is $X" |

In any event the choice needs to be documented in the ontology that defines the key message predicate.

**Comment by pboisver** [comment]
Currently using a manual replacement:

```
        ## Replace placeholders in the template with actual values:
        # Format "[measure name]":
        self.message_text = self.message_text.replace(
            "[measure name]",
            f"{self.sel_measure_title}",
        )
```
