### ISSUE TITLE
create release for current non-working version of the PFKB

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#123]
- create a release with deprecated status
 - clean up main by removing all of non-working files
   -- causal pathways, message templates, input messages

 - leave vignettes in place as they are not processed by the pipeline, but can be removed if necessary

**Comment by pboisver** [comment]
The link for the repo version referenced by the created tag (release) is: https://github.com/Display-Lab/knowledge-base/tree/v1.0.1-deprecated
