### ISSUE TITLE
revise readme to reflect new governance policy

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#124]
write up a statement that indicates that the knowledge base contains tested/working files in the main repo that are working for a specified version of the pipeline. Versioning of the knowledge base may implement breaking changes that need to be recognized with the version of the pipeline. The pipeline depends on a particular version of the knowledge base. Future versions of the knowledge base may not be dependent on the pipeline, and may be developed for other tools independently.

**Comment by mackgalante** [comment]
Created a rough draft blurb in a branch; added text re: the above on the main readme file.

See branch: https://github.com/Display-Lab/knowledge-base/tree/readme-patch-(non-critical)#attention

**Comment by mackgalante** [comment]
Iterated through several times on wording and format
