### ISSUE TITLE
revise vignette moderators

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#138]
- remove habituation and regulatory fit
 - add message recency and delivery as appropriate

**Comment by zachll** [comment]
Proposal: add a moderator to count the number of times this message was sent previously

**Comment by yidanedencao** [comment]
Eden has replaced habituation with message recency and delivery count for all vignettes. Regulatory fit is still listed as a vignette moderator.

**Comment by mackgalante** [comment]
Eden's changes have been merged into main

Should talk about adding number of messages received moderator, otherwise issue is closed :)
