### ISSUE TITLE
update measures.json to include all MPOG process measures

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#167]
- we need to do error handling related to changes in process measures and new measure development
 - monitor https://spec.mpog.org/Measures/Public vs another source of measure changes?

**Comment by zachll** [comment]
Develop an automated process for capturing MPOG measure data

**Comment by mackgalante** [comment]
All measures on MPOG database are added and alphabetized

Leaving automation for a post-pilot goal
