### ISSUE TITLE
Complete goal vignettes

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/knowledge-base#171]
Ready to complete vignettes on goal comparators now that they are implemented in the pipeline

- [x] Complete through esteemer for Goal Loss
- [x] Propagate through pipeline sections for Goal Approach and Goal Gain
- [x] Update tracker

**Comment by 00hchung99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete the KB](https://trello.com/c/RA6RL0cw/3-complete-the-kb)

**Comment by mackgalante** [comment]
Updated infrastructure underlying this issue, have better handle on work to be done:

- [ ] Complete annotations for individual performance data
- [ ] Generate example Esteemer ranks with algorithm
