### ISSUE TITLE
version 3 ideas/roadmap

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#173]
- revisit handling of organization-specific measures, configuration in.env file, and process for adapting the PF knowledge base to a new org

**Comment by zachll** [comment]
- testing of individual pipeline stages

**Comment by zachll** [comment]
- new implementation of candidate smasher that queries the knowledge graph instead of using a combinatoric approach

**Comment by pboisver** [comment]
All items covered in current PFP for MPOG trial
