### ISSUE TITLE
add default display property to message templates

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#181]
Motivation: Message templates are compatible with any display format to accommodate preferences, and they have an optimal display format for each specific message, but these are not yet used by the pipeline.

Suggested approach:
1. Add a property to each message template called "default_display"
2. For templates that are about trends (achievement, loss, approach, improving, and worsening) set the value of the default display to line chart
3. For messages that are not about trends, set the value of the default display to bar chart

**Comment by zachll** [comment]
For messages that have no trend and are about consecutive positive gaps, default to text-only

**Comment by yidanedencao** [comment]
All done
