### ISSUE TITLE
get main up to date with mpog_pilot

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#191]
the main branch of the knowledgebase has become out of date

changes made in the mpog_pilot branch need to be merged back into main

in general, workflow needs to shift from updating mpog_pilot directly to first updating main, and then mpog_pilot

**Comment by pboisver** [comment]
Migrating mpog pilot branch to main is done. No need to maintain a separate branch (pending sustainable localization stragetgy)
