### ISSUE TITLE
message templates need to accurately describe performance levels that are equal to a comparator

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#194]
Motivation: The top performer message template indicates that the recipient's performance level is above the level of the 90th percentile benchmark. However, the benchmark and the recipient's performance level are commonly equal, for example at 100%. This is likely a problem for the 75th percentile message too.

For example: "Your performance was 100.0% (28/28 cases), above the top 10% peer benchmark, which was 100.0% this month."

Proposed solutions:
1. Create a new message that is more vague, like "at or above the top 10% peer benchmark". However, this makes it clear that we don't know what the value is.
2. Develop message templates and causal pathway variants that say "equal to" and which match new preconditions. This would likely require a lot of work, but would make the system sound a lot more intelligent.
3. Find a new wording that doesn't directly address the equal to vs above characteristic, somehow

**Comment by zachll** [comment]
Recommended solution:

Revise all templates that say "above" a comparator to state the performance level of the comparator in a separate and-ed phrase like this:

"You are a top performer this month for the measure [measure name]. Your performance was [recipient performance level] and the top 10% peer benchmark was [comparator performance level]."

**Comment by zachll** [comment]
Next steps:
1. Review message templates in CEDAR to consider changing phrasing from "above" or "below" when performance levels of the recipient and comparator or equal
2. Propose new wording in this issue for each case identified

**Comment by yidanedencao** [comment]
Message templates in CEDAR have been updated with new wording.

**Comment by zachll** [comment]
Changes have been saved in the zachll-patch-1 branch
