### ISSUE TITLE
Create new congratulations message based on top performer and test as the only available message

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#196]
Problem: trend and low performance data is rare in some cases
Solution: Duplicate the "top performer" message template and revise the text to state something like: "Congratulations on your high performance for the measure [X]"

**Comment by pboisver** [comment]
Start with testing top-performer-message-only configuration against the current PFP with (MPOG) data from a couple of months.

**Comment by zachll** [comment]
Added the [new congrats message](https://github.com/Display-Lab/knowledge-base/blob/main/message_templates/congratulations_high_performance.json) to main

**Comment by pboisver** [comment]
Done in mpog pilot and migrated to KB main
