### ISSUE TITLE
post-pilot PFKB clean up

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#203]
There are a few tasks remaining to synchronize and organize the PFKB with regard to files in CEDAR and Github:

 - Move "Opportunity to improve Top 10" message template from mpog_pilot branch to main
 - Update the general message template collection in CEDAR to reduce redundancy and include pilot messages
 -- Update json versions in Github to revise redundant messages

**Comment by 00hchung99** [comment]
Message templates in pilot folder have been moved to the main message template folder in CEDAR. The pilot folder has been deleted and redundant templates in the main message template folder have been archived.

**Comment by 00hchung99** [comment]
Message templates json files have been updated in zachll-patch1 branch. No redundant messages exist now between the set used in pilot and main.

**Comment by pboisver** [comment]
Overtaken by mpog pilot merge activities. We will compare CEDAR templates and the json-ld files in KB main
