### ISSUE TITLE
Rename `mpog_pilot` to `mpog_trial`

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/knowledge-base#218]
Also, we may choose to get rid of the `mpog_trail` branch after we reconcile it with `main` so we should make sure that either the release (with artifacts) is maintained after deleting the branch or the branch should be li=ocked for changes/archived, or something

**Comment by mackgalante** [comment]
Branch rename complete, github should reflect this shortly

**Comment by faridseifi** [comment]
Please do not close this item until the code base is updated pointing to the correct branch. Please do not make any further changes until we are done with the migration of the mpog_trial branch to the main in the knowledge base. It is ok to work on main for documentation but please don't change anything that the pipeline relies on.

**Comment by pboisver** [comment]
This branch is now "retired" and we have all working assets for the mpog trial on the KB main branch. The PFP is currently set up to use v1.4 of the KB, tagged on main. No need to maintain a separate branch—pending work on a sustainable localization strategy.

Closing as done.
