### ISSUE TITLE
add revised persona descriptions to knowledge-base

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#50]
Add the persona descriptions from the [persona spreadsheet](https://docs.google.com/spreadsheets/d/1ZxtuEPI5EVfnO-YcvzGjbUSy3woixCsaz4slOCozVEU/edit#gid=0) to the [vignette readme](https://github.com/Display-Lab/knowledge-base/tree/main/vignettes#readme)
 - this can be directly edited in main

**Comment by 00hchung99** [comment]
Added in descriptions as of 4/26
