### ISSUE TITLE
confirm that message templates have a matching message from the message library

### ISSUE THREAD

**Issue by zachll** [Display-Lab/knowledge-base#96]
Check that both the message template files and the vignettes that describe message templates have a matching message in the message library spreadsheet: https://docs.google.com/spreadsheets/d/1h81ZmTqMWvWDcpLIr5IFW-AAmEiqQAPB4ZtyQtY87HQ/edit#gid=439820594

**Comment by mackgalante** [comment]
- [x] social approach - approach top 10, approach top 25, approach peer avg
- [x] social better - top performer
- [x] social gain - achieved top 10% benchmark, achieved top 25% benchmark, achieved peer avg
- [x] social loss - drop below peer avg, no longer top performer
- [x] social worse - not top performer
- [x] worsening - getting worse, performance dropped
- [ ] improving - 
- [ ] goal gain -

**Comment by mackgalante** [comment]
Message # 16 seems to be missing in Cedar, present in [message library spreadsheet](https://docs.google.com/spreadsheets/d/1h81ZmTqMWvWDcpLIr5IFW-AAmEiqQAPB4ZtyQtY87HQ/edit#gid=439820594)
